[2023-05-06T22:48:00.505+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.ValidateAndLoadSongFact.SongFactToS3 manual__2023-05-06T22:02:18.022658+00:00 [queued]>
[2023-05-06T22:48:00.510+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.ValidateAndLoadSongFact.SongFactToS3 manual__2023-05-06T22:02:18.022658+00:00 [queued]>
[2023-05-06T22:48:00.511+0000] {taskinstance.py:1331} INFO - Starting attempt 13 of 13
[2023-05-06T22:48:00.518+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): ValidateAndLoadSongFact.SongFactToS3> on 2023-05-06 22:02:18.022658+00:00
[2023-05-06T22:48:00.522+0000] {standard_task_runner.py:57} INFO - Started process 1510 to run task
[2023-05-06T22:48:00.526+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'ValidateAndLoadSongFact.SongFactToS3', 'manual__2023-05-06T22:02:18.022658+00:00', '--job-id', '433', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpso7np57e']
[2023-05-06T22:48:00.527+0000] {standard_task_runner.py:85} INFO - Job 433: Subtask ValidateAndLoadSongFact.SongFactToS3
[2023-05-06T22:48:00.561+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.ValidateAndLoadSongFact.SongFactToS3 manual__2023-05-06T22:02:18.022658+00:00 [running]> on host b60ed7c33f68
[2023-05-06T22:48:00.621+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='ValidateAndLoadSongFact.SongFactToS3' AIRFLOW_CTX_EXECUTION_DATE='2023-05-06T22:02:18.022658+00:00' AIRFLOW_CTX_TRY_NUMBER='13' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-06T22:02:18.022658+00:00'
[2023-05-06T22:48:00.634+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/load.py", line 20, in stage_tables
    print(datetime.type)
AttributeError: type object 'datetime.datetime' has no attribute 'type'
[2023-05-06T22:48:00.643+0000] {taskinstance.py:1373} INFO - Marking task as FAILED. dag_id=Summer_Warped_ETL, task_id=ValidateAndLoadSongFact.SongFactToS3, execution_date=20230506T220218, start_date=20230506T224800, end_date=20230506T224800
[2023-05-06T22:48:00.649+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 433 for task ValidateAndLoadSongFact.SongFactToS3 (type object 'datetime.datetime' has no attribute 'type'; 1510)
[2023-05-06T22:48:00.698+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-06T22:48:00.716+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
