[2023-05-08T03:26:43.717+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [queued]>
[2023-05-08T03:26:43.727+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [queued]>
[2023-05-08T03:26:43.728+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 3
[2023-05-08T03:26:43.740+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadSongDim> on 2023-05-08 03:26:11.627191+00:00
[2023-05-08T03:26:43.745+0000] {standard_task_runner.py:57} INFO - Started process 1708 to run task
[2023-05-08T03:26:43.751+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadSongDim', 'manual__2023-05-08T03:26:11.627191+00:00', '--job-id', '1800', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpxy9vo_km']
[2023-05-08T03:26:43.752+0000] {standard_task_runner.py:85} INFO - Job 1800: Subtask LoadData.LoadSongDim
[2023-05-08T03:26:43.810+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [running]> on host a40687a10d43
[2023-05-08T03:26:43.885+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadSongDim' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T03:26:11.627191+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T03:26:11.627191+00:00'
[2023-05-08T03:26:43.888+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_database() missing 1 required positional argument: 'primary_key'
[2023-05-08T03:26:43.897+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadSongDim, execution_date=20230508T032611, start_date=20230508T032643, end_date=20230508T032643
[2023-05-08T03:26:43.907+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1800 for task LoadData.LoadSongDim (upload_to_database() missing 1 required positional argument: 'primary_key'; 1708)
[2023-05-08T03:26:43.922+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T03:26:43.947+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
