[2023-05-08T03:27:15.118+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [queued]>
[2023-05-08T03:27:15.124+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [queued]>
[2023-05-08T03:27:15.124+0000] {taskinstance.py:1331} INFO - Starting attempt 2 of 3
[2023-05-08T03:27:15.134+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadSongDim> on 2023-05-08 03:26:11.627191+00:00
[2023-05-08T03:27:15.141+0000] {standard_task_runner.py:57} INFO - Started process 1723 to run task
[2023-05-08T03:27:15.146+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadSongDim', 'manual__2023-05-08T03:26:11.627191+00:00', '--job-id', '1803', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmpldd98k8y']
[2023-05-08T03:27:15.147+0000] {standard_task_runner.py:85} INFO - Job 1803: Subtask LoadData.LoadSongDim
[2023-05-08T03:27:15.189+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T03:26:11.627191+00:00 [running]> on host a40687a10d43
[2023-05-08T03:27:15.249+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadSongDim' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T03:26:11.627191+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T03:26:11.627191+00:00'
[2023-05-08T03:27:15.251+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_database() missing 1 required positional argument: 'primary_key'
[2023-05-08T03:27:15.259+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadSongDim, execution_date=20230508T032611, start_date=20230508T032715, end_date=20230508T032715
[2023-05-08T03:27:15.266+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1803 for task LoadData.LoadSongDim (upload_to_database() missing 1 required positional argument: 'primary_key'; 1723)
[2023-05-08T03:27:15.278+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T03:27:15.297+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
