[2023-05-08T03:26:43.751+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T01:09:52.601148+00:00 [queued]>
[2023-05-08T03:26:43.759+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T01:09:52.601148+00:00 [queued]>
[2023-05-08T03:26:43.759+0000] {taskinstance.py:1331} INFO - Starting attempt 4 of 6
[2023-05-08T03:26:43.770+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): LoadData.LoadSongDim> on 2023-05-08 01:09:52.601148+00:00
[2023-05-08T03:26:43.776+0000] {standard_task_runner.py:57} INFO - Started process 1709 to run task
[2023-05-08T03:26:43.782+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Summer_Warped_ETL', 'LoadData.LoadSongDim', 'manual__2023-05-08T01:09:52.601148+00:00', '--job-id', '1801', '--raw', '--subdir', 'DAGS_FOLDER/warped-dag.py', '--cfg-path', '/tmp/tmp04e2rysy']
[2023-05-08T03:26:43.783+0000] {standard_task_runner.py:85} INFO - Job 1801: Subtask LoadData.LoadSongDim
[2023-05-08T03:26:43.831+0000] {task_command.py:410} INFO - Running <TaskInstance: Summer_Warped_ETL.LoadData.LoadSongDim manual__2023-05-08T01:09:52.601148+00:00 [running]> on host a40687a10d43
[2023-05-08T03:26:43.912+0000] {taskinstance.py:1570} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ananta Moharana' AIRFLOW_CTX_DAG_ID='Summer_Warped_ETL' AIRFLOW_CTX_TASK_ID='LoadData.LoadSongDim' AIRFLOW_CTX_EXECUTION_DATE='2023-05-08T01:09:52.601148+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-05-08T01:09:52.601148+00:00'
[2023-05-08T03:26:43.916+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: upload_to_database() missing 1 required positional argument: 'primary_key'
[2023-05-08T03:26:43.925+0000] {taskinstance.py:1373} INFO - Marking task as UP_FOR_RETRY. dag_id=Summer_Warped_ETL, task_id=LoadData.LoadSongDim, execution_date=20230508T010952, start_date=20230508T032643, end_date=20230508T032643
[2023-05-08T03:26:43.935+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 1801 for task LoadData.LoadSongDim (upload_to_database() missing 1 required positional argument: 'primary_key'; 1709)
[2023-05-08T03:26:43.953+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-05-08T03:26:44.001+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
